# Changes here will be overwritten by Copier
_commit: v1.3
_src_path: https://github.com/acid9reen/python_template
author: Ruslan Smirnov
package_name: dat2npy
project_name: .dat to .npy converter
project_short_description: Set of scripts to convert .dat files to .npy (also labels
    for dataset generation)
python_version: '3.10'

